//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.21 at 04:51:50 PM CST 
//


/**
 * beanToXml
 * 时间：2018-1-21
 * @author quiet
 * 
 * jaxbUtils  使用该类
 */
@XmlSchema(
		//配置
		namespace = "",
		elementFormDefault = XmlNsForm.QUALIFIED
		)
package red.silence.utils.common;
import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;

